# Generated by Django 5.0.2 on 2024-07-01 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='host',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/Blog-images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
