# Generated by Django 5.0.2 on 2024-07-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_host_alter_comment_blog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='host',
        ),
    ]
